version: "3"

services:

  runtime-setup:
    image: swift-metrics:22.04-5.10
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.10-jammy"


  test:
    image: swift-metrics:22.04-5.10
    environment:
      - FORCE_TEST_DISCOVERY=--enable-test-discovery
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-metrics:22.04-5.10
